# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f1de20f22c713dce59c4fa7bd0bc662019b459b7b240a5194e79105d696089a020bdf4865035f39acb7d543518c992999d8c1e6f4f58e0c8a6849131c1f019

test:
  secret_key_base: feb8de51c23b222b2e740949f8549646a3c91bbd5a90f2429c640373c78ba6e7d107ca98987b206911e15e4176fe04867dc319913dd594d11172bedc9f691909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
